### PR TITLE
Update

### PR DESCRIPTION
**Pull request by ocefpaf**
```
2.0.1

This minor release contains a new seaname list and a bug fix to setup.py
```

```
2.0.0

Adds checkers to support the [NCEI NetCDF templates v2.0](https://www.nodc.noaa.gov/data/formats/netcdf/v2.0/) for the following feature types:

- point
- timeSeries
- trajectory
- profile
- timeSeriesProfile
- trajectoryProfile
- grid

Updates the global sea_name attribute check to query the NCEI vocabulary lookup service
Drops check for allowable variable names for elevation variable
Drops requirement for a comment attribute

Support for swath feature types will be added once NCEI guidance is in place.
```

### CODE REVIEW

**Comment by ocefpaf** [comment]
@lukecampbell I add a new command line test `compliance-checker -t ncei-trajectoryprofile-orthogonal -v https://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/GOLD_STANDARD_NETCDF/1.1/NODC_trajectoryProfile_template_v1.1_2016-06-15_133721.704494.nc` and it is failing with:

```
+ compliance-checker -t ncei-trajectoryprofile-orthogonal -v https://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/GOLD_STANDARD_NETCDF/1.1/NODC_trajectoryProfile_template_v1.1_2016-06-15_133721.704494.nc
Running Compliance Checker on the dataset from: https://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/GOLD_STANDARD_NETCDF/1.1/NODC_trajectoryProfile_template_v1.1_2016-06-15_133721.704494.nc
No valid checkers found for tests 'ncei-trajectoryprofile-orthogonal'
Traceback (most recent call last):
  File "/opt/conda/envs/_test/bin/compliance-checker", line 6, in <module>
    sys.exit(cchecker.main())
  File "/opt/conda/envs/_test/bin/cchecker.py", line 73, in main
    args.format)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/compliance_checker/runner.py", line 62, in run_checker
    groups = cls.stdout_output(cs, score_groups, verbose, limit)
  File "/opt/conda/envs/_test/lib/python2.7/site-packages/compliance_checker/runner.py", line 103, in stdout_output
    return groups
UnboundLocalError: local variable 'groups' referenced before assignment
TESTS FAILED: cc-plugin-ncei-2.0.0-py27_0
```

Is that a real failure of the test is wrong? Note that I had to change the URL from the README b/c that one no longer exists.

**Comment by lukecampbell** [comment]
That looks like a very old bug in compliance checker. Do you know what version of compliance checker got downloaded?

**Comment by ocefpaf** [comment]
> That looks like a very old bug in compliance checker. Do you know what version of compliance checker got downloaded?

It is 2.3.0. See https://travis-ci.org/conda-forge/cc-plugin-ncei-feedstock/jobs/172355655#L530

**Comment by lukecampbell** [comment]
Give me a few minutes, I'll release a 2.3.1 with the fix... I thought we fixed this long ago.

**Comment by lukecampbell** [comment]
So the symptom shown in the test is because there is no check `ncei-trajectoryprofile-orthogonal` the check name is `ncei-trajectory-profile-orthogonal`. Unfortunately it manifests itself in a very unclear manner.

**Comment by lukecampbell** [comment]
@Bobfrat could you look into this?

**Comment by ocefpaf** [comment]
```
2.0.1

This minor release contains a new seaname list and a bug fix to setup.py
```

**Comment by ocefpaf** [comment]
The CLI call worked but because it returns a non-zero exit code we cannot use for testing here. See

```
+ /bin/bash -x -e /feedstock_root/build_artefacts/test-tmp_dir/run_test.sh
+ compliance-checker -t ncei-trajectory-profile-orthogonal -v https://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/GOLD_STANDARD_NETCDF/1.1/NODC_trajectoryProfile_template_v1.1_2016-06-15_133721.704494.nc
Running Compliance Checker on the dataset from: https://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/GOLD_STANDARD_NETCDF/1.1/NODC_trajectoryProfile_template_v1.1_2016-06-15_133721.704494.nc


--------------------------------------------------------------------------------
                    The dataset scored 108 out of 117 points                    
              during the ncei-trajectory-profile-orthogonal check               
--------------------------------------------------------------------------------
                           Verbose Scoring Breakdown:                            

                                 High Priority                                  
--------------------------------------------------------------------------------
    Name                            :Priority: Score
All geophysical variables are trajector :3:     2/2
Highly Recommended global attributes    :3:     3/3
Required Global Attributes for Trajecto :3:     2/3
Required attributes for variable lat    :3:     3/3
Required attributes for variable lon    :3:     3/3
Required attributes for variable sal    :3:     3/3
Required attributes for variable temp   :3:     3/3
Required attributes for variable time   :3:     3/3
Required attributes for variable z      :3:     4/4
Required global attributes              :3:     1/2


                                Medium Priority                                 
--------------------------------------------------------------------------------
    Name                            :Priority: Score
Recommended attributes for coordinate v :2:     3/3
Recommended attributes for grid mapping :2:     4/4
Recommended attributes for instrument v :2:     2/2
Recommended attributes for platform var :2:     4/4
Recommended attributes for the trajecto :2:     1/1
Recommended attributes for variable lat :2:     6/6
Recommended attributes for variable lon :2:     5/5
Recommended attributes for variable sal :2:    11/12
Recommended attributes for variable tem :2:    11/12
Recommended attributes for variable tim :2:     2/2
Recommended global attributes           :2:    31/36
Variable defining "trajectory_id" exist :2:     1/1


                                  Low Priority                                  
--------------------------------------------------------------------------------
    Name                            :Priority: Score
Suggested global attributes             :1:    19/28


--------------------------------------------------------------------------------
                  Reasoning for the failed tests given below:                   


Name                             Priority:     Score:Reasoning
--------------------------------------------------------------------------------
Required Global Attributes for Trajecto:3:     2/ 3 : ncei_template_version
                                                      attribute must be NCEI_Net
                                                      CDF_TrajectoryProfile_Orth
                                                      ogonal_Template_v2.0
Required global attributes             :3:     1/ 2 : Conventions attribute is
                                                      missing or is not equal to
                                                      "CF-1.6, ACDD-1.3": CF-1.6
Recommended attributes for variable sal:2:    11/12 : coverage_content_type
                                                      should exist and be one of
                                                      the following:image,
                                                      thematicClassification,
                                                      physicalMeasurement,
                                                      auxiliaryInformation,
                                                      qualityInformation,
                                                      referenceInformation,
                                                      modelResult, or coordinate
Recommended attributes for variable tem:2:    11/12 : coverage_content_type
                                                      should exist and be one of
                                                      the following:image,
                                                      thematicClassification,
                                                      physicalMeasurement,
                                                      auxiliaryInformation,
                                                      qualityInformation,
                                                      referenceInformation,
                                                      modelResult, or coordinate
Recommended global attributes          :2:    31/36 : geospatial_bounds should
                                                      exist and not be empty.,
                                                      geospatial_bounds_crs
                                                      should exist and not be
                                                      empty., geospatial_bounds_
                                                      vertical_crs should exist
                                                      and not be empty.,
                                                      time_coverage_duration
                                                      should exist and be
                                                      ISO-8601 format (example:
                                                      PT1M30S), currently:
                                                      PT1M30.S,
                                                      time_coverage_resolution
                                                      should exist and be
                                                      ISO-8601 format (example:
                                                      PT1M30S), currently:
                                                      PT10.S
Suggested global attributes            :1:    19/28 : date_metadata_modified
                                                      should exist and be
                                                      ISO-8601 format (example:
                                                      PT1M30S), currently: ,
                                                      creator_type should exist
                                                      and not be empty.,
                                                      creator_institution should
                                                      exist and not be empty.,
                                                      publisher_type should
                                                      exist and not be empty.,
                                                      publisher_institution
                                                      should exist and not be
                                                      empty., program should
                                                      exist and not be empty.,
                                                      product_version should
                                                      exist and not be empty.,
                                                      platform_vocabulary should
                                                      exist and not be empty.,
                                                      instrument_vocabulary
                                                      should exist and not be
                                                      empty.
TESTS FAILED: cc-plugin-ncei-2.0.1-py27_0

./ci_support/run_docker_build.sh returned exit code 1

```

@lukecampbell is that because the dataset hasis failing? Do we have a real `GOLD_STANDARD_NETCDF`  :wink: that passes? Would that return a `0` exit code? What is the meaning of life? Can we return `42` instead? :stuck_out_tongue_winking_eye:

**Comment by daf** [comment]
Why not just `|| true` the call if we know it will fail?

**Comment by ocefpaf** [comment]
> Why not just `|| true` the call if we know it will fail?

Because other failures, like the one that lead to `2.0.1` would be ignored.

**Comment by Bobfrat** [comment]
There is such thing as a perfect score:
```compliance-checker -t ncei-trajectory -v https://data.nodc.noaa.gov/thredds/dodsC/testdata/mbiddle/GOLD_STANDARD_NETCDF/1.1/NODC_trajectory_template_v1.1_2016-06-15_133719.365561.nc```

**Comment by ocefpaf** [comment]
> There is such thing as a perfect score:

Awesome! That one returns `0`. Let me know if you recommend running more CLI tests here. I see that there are many entrypoints in the `setup.py` and I chose that one only because it was in the readme.

**Comment by ocefpaf** [comment]
Not there yet @Bobfrat.  `The dataset scored 109 out of 118 points` :smile:

**Comment by Bobfrat** [comment]
@ocefpaf looks like the last circleci test scored 128 out of 128.

screen shot 2016-11-02 at 3 40 37 pm

**Comment by ocefpaf** [comment]
> @ocefpaf looks like the last circleci test scored 128 out of 128.

Not in the previous run.

ccncei

As you can see from https://github.com/conda-forge/cc-plugin-ncei-feedstock/pull/5/commits/282e9a70bb7a023f148b14dee74dc320a65a7da3 the only change was `|| true  # [not win]`.  Maybe the data change in between runs.

**Comment by lukecampbell** [comment]
Can you post the links here? I'd like to get to the bottom of this.

**Comment by ocefpaf** [comment]
Just follow the last two commits:

https://github.com/conda-forge/cc-plugin-ncei-feedstock/pull/5/commits

**Comment by lukecampbell** [comment]
Wow, that's a tricky one. The only difference I see in the execution is one is py34, the other is py35. But the REALLY odd bits is that the number of points available changed.

**Pull request merged**
